#!/usr/bin/env bash

DEPS=(gdb)

help() {
  echo "Usage: ${0##*/} <pid>" 1>&2

  exit 1
}

die() {
  [[ ! -z "${1}" ]] && echo -e "\e[0;31m${1}\e[0m" 1>&2

  exit 1
}

deps() {
  for i in ${DEPS[@]}; do
    `command -v ${i} > /dev/null 2>&1` || die "${i} is not installed!"
  done
}

deps

( [[ ${#} -ne 1 ]] || [[ ! ${1} =~ ^[0-9]+$ ]] ) && help

[[ ${EUID} -ne 0 ]] && pf="sudo "

${pf}gdb --ex "thread apply all bt" --batch -p ${1} 2>&1 | \
  grep -Pzo "(?s)Thread \d+.+"
